spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001  
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.pro.domain
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring: 
  profiles: dev
  application: 
    name: cloud-config-dept-client   
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud1
    username: root
    password: root
    dbcp2:
      min-idle: 5   #最小连接数
      initial-size: 5 #初始化连接数
      max-total: 5 
      max-wait-millis: 200  
      
eureka:
  client: 
    service-url:
      #defaultZone: http://localhost:8003/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true           #显示ip地址
    
info: 
  app.name: cloud-dept-provider
  company.name: wwww.ycznz.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 8001  
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.pro.domain
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring: 
  profiles: test
  application: 
    name: cloud-config-dept-client   
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2
    username: root
    password: root
    dbcp2:
      min-idle: 5   #最小连接数
      initial-size: 5 #初始化连接数
      max-total: 5 
      max-wait-millis: 200  
      
eureka:
  client: 
    service-url:
      #defaultZone: http://localhost:8003/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true           #显示ip地址
    
info: 
  app.name: cloud-dept-provider
  company.name: wwww.ycznz.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$


