spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8001
spring: 
  profiles: dev
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud1
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5 
      max-total: 5
      max-wait-millis: 200
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.pro.domain
  mapper-locations:
  - classpath: mybatis/mapper/**/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info: 
  app.name: cloud-dept-provider
  company.name: wwww.ycznz.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring: 
  profiles: test
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5 
      max-total: 5
      max-wait-millis: 200
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.pro.domain
  mapper-locations:
  - classpath: mybatis/mapper/**/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info: 
  app.name: cloud-dept-provider
  company.name: wwww.ycznz.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$   
